<a href="https://colab.research.google.com/github/mcampb89-tech/Intro-to-machine-learning/blob/main/Python_assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#List Methods



In [1]:
nums = [10,20,30,40]

nums.append(50)
print(nums)
nums.pop()
print(nums)
nums.reverse()
print(nums)


[10, 20, 30, 40, 50]
[10, 20, 30, 40]
[40, 30, 20, 10]


#Numpy

In [9]:
import numpy as np

np.random.seed(100)
ar_1d = np.random.rand(25)

ar_2d=ar_1d.reshape(5,5)

squared_matrix = ar_2d ** 2

small = squared_matrix [ squared_matrix < 1e-2]

indices = np.where(squared_matrix < 1e-2)

print("original 1d", ar_1d)
print("5x5",ar_2d)
print("squared matrix", squared_matrix)
print("small values", small)
print("indices", indices)

original 1d [0.54340494 0.27836939 0.42451759 0.84477613 0.00471886 0.12156912
 0.67074908 0.82585276 0.13670659 0.57509333 0.89132195 0.20920212
 0.18532822 0.10837689 0.21969749 0.97862378 0.81168315 0.17194101
 0.81622475 0.27407375 0.43170418 0.94002982 0.81764938 0.33611195
 0.17541045]
5x5 [[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]
 [0.12156912 0.67074908 0.82585276 0.13670659 0.57509333]
 [0.89132195 0.20920212 0.18532822 0.10837689 0.21969749]
 [0.97862378 0.81168315 0.17194101 0.81622475 0.27407375]
 [0.43170418 0.94002982 0.81764938 0.33611195 0.17541045]]
squared matrix [[2.95288931e-01 7.74895146e-02 1.80215185e-01 7.13646714e-01
  2.22676038e-05]
 [1.47790511e-02 4.49904335e-01 6.82032773e-01 1.86886917e-02
  3.30732338e-01]
 [7.94454826e-01 4.37655279e-02 3.43465490e-02 1.17455504e-02
  4.82669883e-02]
 [9.57704512e-01 6.58829535e-01 2.95637119e-02 6.66222840e-01
  7.51164188e-02]
 [1.86368502e-01 8.83656062e-01 6.68550507e-01 1.12971243e-01
  3.07688273e-0